version: '{branch}-{build}'
build: off
configuration: Release
environment:
  matrix:
    - TESTENV: 'py27-64'
      PYTHON_VERSION: '2.7'
      PYTHON: C:\Miniconda27-x64

    - TESTENV: 'py27-32'
      PYTHON_VERSION: '2.7'
      PYTHON: C:\Miniconda27


#init:
install:
  - 'SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH'
  - 'conda config --set always_yes yes'
  - 'conda update -q conda'
  - 'conda create -q -n test python=%PYTHON_VERSION% pytest pip'
  - 'activate test'
  - 'pip install -r requirements.txt'
  - 'pip install -q -e .'
test_script:
  - 'py.test tests'

